import { InventoryItem, Recipe } from '@/src/types';

export const mockInventory: InventoryItem[] = [
  { id: 1, name: 'Tomaat', category: 'Groente', quantity: 4 },
  { id: 2, name: 'Ui', category: 'Groente', quantity: 2 },
  { id: 3, name: 'Kipfilet', category: 'Vlees', quantity: 500, unit: 'g' },
  { id: 4, name: 'Rijst', category: 'Graan', quantity: 1, unit: 'kg' },
  { id: 5, name: 'Olijfolie', category: 'Vet', quantity: 1, unit: 'fles' },
];

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: 'Kippen Curry met Rijst',
    description: 'Een romige curry met kip en groenten',
    prepTime: 35,
    servings: 4,
    difficulty: 'Makkelijk',
    ingredients: [
      { name: 'Kipfilet', amount: 500, unit: 'g' },
      { name: 'Rijst', amount: 300, unit: 'g' },
      { name: 'Ui', amount: 1, unit: 'stuk' },
      { name: 'Tomaat', amount: 2, unit: 'stuk' },
      { name: 'Kokosmelk', amount: 400, unit: 'ml' },
      { name: 'Currypoeder', amount: 2, unit: 'tl' },
    ],
    steps: [
      'Snijd de kip in blokjes',
      'Fruit de ui in olijfolie',
      'Voeg kip toe en bak 5 minuten',
      'Voeg currypoeder en tomaten toe',
      'Giet kokosmelk erbij en laat 20 minuten sudderen',
      'Kook de rijst volgens de instructies',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    tags: ['snel'],
  },
  {
    id: 2,
    title: 'Pasta Carbonara',
    description: 'Klassieke Italiaanse pasta met spek en ei',
    prepTime: 25,
    servings: 4,
    difficulty: 'Gemiddeld',
    ingredients: [
      { name: 'Pasta', amount: 400, unit: 'g' },
      { name: 'Spek', amount: 200, unit: 'g' },
      { name: 'Eieren', amount: 4, unit: 'stuk' },
      { name: 'Parmezaanse kaas', amount: 100, unit: 'g' },
      { name: 'Zwarte peper', amount: 1, unit: 'tl' },
    ],
    steps: [
      'Kook de pasta volgens de instructies',
      'Bak het spek krokant in een pan',
      'Klop de eieren met geraspte kaas',
      'Meng pasta met spek (van het vuur)',
      'Voeg het eimengsel toe en roer snel',
      'Bestrooi met peper en serveer',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    tags: ['snel'],
  },
  {
    id: 3,
    title: 'Groente Risotto',
    description: 'Romige risotto met verse groenten',
    prepTime: 45,
    servings: 4,
    difficulty: 'Gemiddeld',
    ingredients: [
      { name: 'Risottorijst', amount: 300, unit: 'g' },
      { name: 'Ui', amount: 1, unit: 'stuk' },
      { name: 'Knoflook', amount: 2, unit: 'teentjes' },
      { name: 'Groentebouillon', amount: 1, unit: 'liter' },
      { name: 'Witte wijn', amount: 100, unit: 'ml' },
      { name: 'Parmezaanse kaas', amount: 50, unit: 'g' },
      { name: 'Olijfolie', amount: 2, unit: 'el' },
    ],
    steps: [
      'Fruit ui en knoflook in olijfolie',
      'Voeg risottorijst toe en bak 2 minuten',
      'Voeg witte wijn toe en laat verdampen',
      'Voeg beetje bij beetje bouillon toe en roer',
      'Blijf roeren tot rijst zacht is (20-25 min)',
      'Roer kaas erdoor en serveer',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800',
    tags: ['vegetarisch'],
  },
  {
    id: 4,
    title: 'Tomatensoep',
    description: 'Huisgemaakte tomatensoep met verse kruiden',
    prepTime: 30,
    servings: 4,
    difficulty: 'Makkelijk',
    ingredients: [
      { name: 'Tomaat', amount: 6, unit: 'stuk' },
      { name: 'Ui', amount: 1, unit: 'stuk' },
      { name: 'Knoflook', amount: 2, unit: 'teentjes' },
      { name: 'Groentebouillon', amount: 500, unit: 'ml' },
      { name: 'Basilicum', amount: 10, unit: 'blaadjes' },
      { name: 'Olijfolie', amount: 2, unit: 'el' },
    ],
    steps: [
      'Snijd tomaten in kwarten',
      'Fruit ui en knoflook in olijfolie',
      'Voeg tomaten toe en bak 5 minuten',
      'Voeg bouillon toe en kook 15 minuten',
      'Pureer met staafmixer',
      'Bestrooi met basilicum en serveer',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    tags: ['vegetarisch', 'snel'],
  },
  {
    id: 5,
    title: 'Geroosterde Kip met Groenten',
    description: 'Malse kip uit de oven met geroosterde groenten',
    prepTime: 60,
    servings: 4,
    difficulty: 'Makkelijk',
    ingredients: [
      { name: 'Kipfilet', amount: 600, unit: 'g' },
      { name: 'Tomaat', amount: 4, unit: 'stuk' },
      { name: 'Paprika', amount: 2, unit: 'stuk' },
      { name: 'Ui', amount: 2, unit: 'stuk' },
      { name: 'Olijfolie', amount: 3, unit: 'el' },
      { name: 'Kruidenmix', amount: 2, unit: 'tl' },
    ],
    steps: [
      'Verwarm oven voor op 200°C',
      'Snijd groenten in stukken',
      'Meng kip en groenten met olie en kruiden',
      'Leg alles op bakplaat',
      'Rooster 40-45 minuten in oven',
      'Serveer direct uit de oven',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800',
    tags: [],
  },
];




